// Code generated by mockery v2.53.6. DO NOT EDIT.

package link

import (
	context "context"

	model "github.com/kytruongdev/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountByCreatorIPSince provides a mock function with given fields: ctx, ip, since
func (_m *MockRepository) CountByCreatorIPSince(ctx context.Context, ip string, since time.Time) (int, error) {
	ret := _m.Called(ctx, ip, since)

	if len(ret) == 0 {
		panic("no return value specified for CountByCreatorIPSince")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return rf(ctx, ip, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = rf(ctx, ip, since)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, ip, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountByCreatorIPSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCreatorIPSince'
type MockRepository_CountByCreatorIPSince_Call struct {
	*mock.Call
}

// CountByCreatorIPSince is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
//   - since time.Time
func (_e *MockRepository_Expecter) CountByCreatorIPSince(ctx interface{}, ip interface{}, since interface{}) *MockRepository_CountByCreatorIPSince_Call {
	return &MockRepository_CountByCreatorIPSince_Call{Call: _e.mock.On("CountByCreatorIPSince", ctx, ip, since)}
}

func (_c *MockRepository_CountByCreatorIPSince_Call) Run(run func(ctx context.Context, ip string, since time.Time)) *MockRepository_CountByCreatorIPSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_CountByCreatorIPSince_Call) Return(_a0 int, _a1 error) *MockRepository_CountByCreatorIPSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountByCreatorIPSince_Call) RunAndReturn(run func(context.Context, string, time.Time) (int, error)) *MockRepository_CountByCreatorIPSince_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Create(ctx context.Context, _a1 model.Link) (model.Link, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Link) (model.Link, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Link) model.Link); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Link) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.Link
func (_e *MockRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, _a1 model.Link)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Link))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 model.Link, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, model.Link) (model.Link, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockRepository) GetByCode(ctx context.Context, code string) (model.Link, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Link, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Link); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *MockRepository_GetByCode_Call {
	return &MockRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *MockRepository_GetByCode_Call) Run(run func(ctx context.Context, code string)) *MockRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByCode_Call) Return(_a0 model.Link, _a1 error) *MockRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByCode_Call) RunAndReturn(run func(context.Context, string) (model.Link, error)) *MockRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNormalizedURL provides a mock function with given fields: ctx, normalizedURL
func (_m *MockRepository) GetByNormalizedURL(ctx context.Context, normalizedURL string) (model.Link, error) {
	ret := _m.Called(ctx, normalizedURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByNormalizedURL")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Link, error)); ok {
		return rf(ctx, normalizedURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Link); ok {
		r0 = rf(ctx, normalizedURL)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, normalizedURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByNormalizedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNormalizedURL'
type MockRepository_GetByNormalizedURL_Call struct {
	*mock.Call
}

// GetByNormalizedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - normalizedURL string
func (_e *MockRepository_Expecter) GetByNormalizedURL(ctx interface{}, normalizedURL interface{}) *MockRepository_GetByNormalizedURL_Call {
	return &MockRepository_GetByNormalizedURL_Call{Call: _e.mock.On("GetByNormalizedURL", ctx, normalizedURL)}
}

func (_c *MockRepository_GetByNormalizedURL_Call) Run(run func(ctx context.Context, normalizedURL string)) *MockRepository_GetByNormalizedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByNormalizedURL_Call) Return(_a0 model.Link, _a1 error) *MockRepository_GetByNormalizedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByNormalizedURL_Call) RunAndReturn(run func(context.Context, string) (model.Link, error)) *MockRepository_GetByNormalizedURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]model.Link, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Link, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Link); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockRepository_ListByUserID_Call {
	return &MockRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListByUserID_Call) Return(_a0 []model.Link, _a1 error) *MockRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Link, error)) *MockRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
