// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlc

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (code, original_url, normalized_url)
VALUES ($1, $2, $3)
RETURNING code, original_url, normalized_url, created_at
`

type CreateLinkParams struct {
	Code          string
	OriginalUrl   string
	NormalizedUrl string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Code, arg.OriginalUrl, arg.NormalizedUrl)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.OriginalUrl,
		&i.NormalizedUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getByCode = `-- name: GetByCode :one
SELECT code, original_url, normalized_url, created_at FROM links
WHERE code = $1
`

func (q *Queries) GetByCode(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getByCode, code)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.OriginalUrl,
		&i.NormalizedUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getByNormalizedURL = `-- name: GetByNormalizedURL :one
SELECT code, original_url, normalized_url, created_at FROM links
WHERE normalized_url = $1
`

func (q *Queries) GetByNormalizedURL(ctx context.Context, normalizedUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getByNormalizedURL, normalizedUrl)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.OriginalUrl,
		&i.NormalizedUrl,
		&i.CreatedAt,
	)
	return i, err
}
