// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Link struct {
	Code          string
	OriginalUrl   string
	NormalizedUrl string
	CreatedAt     time.Time
}
