// Code generated by mockery v2.53.6. DO NOT EDIT.

package link

import (
	context "context"

	model "github.com/kytruongdev/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: ctx, code
func (_m *MockController) Decode(ctx context.Context, code string) (model.Link, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Link, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Link); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockController_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockController_Expecter) Decode(ctx interface{}, code interface{}) *MockController_Decode_Call {
	return &MockController_Decode_Call{Call: _e.mock.On("Decode", ctx, code)}
}

func (_c *MockController_Decode_Call) Run(run func(ctx context.Context, code string)) *MockController_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockController_Decode_Call) Return(_a0 model.Link, _a1 error) *MockController_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Decode_Call) RunAndReturn(run func(context.Context, string) (model.Link, error)) *MockController_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function with given fields: ctx, rawURL, userID, clientIP
func (_m *MockController) Encode(ctx context.Context, rawURL string, userID *uuid.UUID, clientIP string) (model.Link, error) {
	ret := _m.Called(ctx, rawURL, userID, clientIP)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID, string) (model.Link, error)); ok {
		return rf(ctx, rawURL, userID, clientIP)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID, string) model.Link); ok {
		r0 = rf(ctx, rawURL, userID, clientIP)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uuid.UUID, string) error); ok {
		r1 = rf(ctx, rawURL, userID, clientIP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockController_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - ctx context.Context
//   - rawURL string
//   - userID *uuid.UUID
//   - clientIP string
func (_e *MockController_Expecter) Encode(ctx interface{}, rawURL interface{}, userID interface{}, clientIP interface{}) *MockController_Encode_Call {
	return &MockController_Encode_Call{Call: _e.mock.On("Encode", ctx, rawURL, userID, clientIP)}
}

func (_c *MockController_Encode_Call) Run(run func(ctx context.Context, rawURL string, userID *uuid.UUID, clientIP string)) *MockController_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockController_Encode_Call) Return(_a0 model.Link, _a1 error) *MockController_Encode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Encode_Call) RunAndReturn(run func(context.Context, string, *uuid.UUID, string) (model.Link, error)) *MockController_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockController) ListByUser(ctx context.Context, userID uuid.UUID) ([]model.Link, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Link, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Link); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockController_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockController_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockController_ListByUser_Call {
	return &MockController_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockController_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockController_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockController_ListByUser_Call) Return(_a0 []model.Link, _a1 error) *MockController_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Link, error)) *MockController_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx, code
func (_m *MockController) Resolve(ctx context.Context, code string) (model.Link, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 model.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Link, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Link); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(model.Link)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockController_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockController_Expecter) Resolve(ctx interface{}, code interface{}) *MockController_Resolve_Call {
	return &MockController_Resolve_Call{Call: _e.mock.On("Resolve", ctx, code)}
}

func (_c *MockController_Resolve_Call) Run(run func(ctx context.Context, code string)) *MockController_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockController_Resolve_Call) Return(_a0 model.Link, _a1 error) *MockController_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Resolve_Call) RunAndReturn(run func(context.Context, string) (model.Link, error)) *MockController_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
