// Code generated by mockery v2.53.6. DO NOT EDIT.

package token

import (
	context "context"

	model "github.com/kytruongdev/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Create(ctx context.Context, _a1 model.RefreshToken) (model.RefreshToken, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RefreshToken) (model.RefreshToken, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RefreshToken) model.RefreshToken); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RefreshToken) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.RefreshToken
func (_e *MockRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, _a1 model.RefreshToken)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RefreshToken))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 model.RefreshToken, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, model.RefreshToken) (model.RefreshToken, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRepository) GetByHash(ctx context.Context, tokenHash string) (model.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 model.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockRepository_GetByHash_Call {
	return &MockRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByHash_Call) Return(_a0 model.RefreshToken, _a1 error) *MockRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (model.RefreshToken, error)) *MockRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, tokenHash
func (_m *MockRepository) Revoke(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRepository_Expecter) Revoke(ctx interface{}, tokenHash interface{}) *MockRepository_Revoke_Call {
	return &MockRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, tokenHash)}
}

func (_c *MockRepository_Revoke_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Revoke_Call) Return(_a0 error) *MockRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
