// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockController) Login(ctx context.Context, email string, password string) (AuthResult, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (AuthResult, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) AuthResult); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(AuthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockController_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockController_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockController_Login_Call {
	return &MockController_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockController_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockController_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockController_Login_Call) Return(_a0 AuthResult, _a1 error) *MockController_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Login_Call) RunAndReturn(run func(context.Context, string, string) (AuthResult, error)) *MockController_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockController) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockController_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockController_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockController_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockController_Logout_Call {
	return &MockController_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockController_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockController_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockController_Logout_Call) Return(_a0 error) *MockController_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockController_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockController_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockController) Refresh(ctx context.Context, refreshToken string) (AuthResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (AuthResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) AuthResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(AuthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockController_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockController_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockController_Refresh_Call {
	return &MockController_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockController_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockController_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockController_Refresh_Call) Return(_a0 AuthResult, _a1 error) *MockController_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Refresh_Call) RunAndReturn(run func(context.Context, string) (AuthResult, error)) *MockController_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password
func (_m *MockController) Register(ctx context.Context, email string, password string) (AuthResult, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (AuthResult, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) AuthResult); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(AuthResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockController_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockController_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockController_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *MockController_Register_Call {
	return &MockController_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *MockController_Register_Call) Run(run func(ctx context.Context, email string, password string)) *MockController_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockController_Register_Call) Return(_a0 AuthResult, _a1 error) *MockController_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockController_Register_Call) RunAndReturn(run func(context.Context, string, string) (AuthResult, error)) *MockController_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
